name: nod2
on:
  schedule:
    - cron: '5 4/8 * * *'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: estupida/test:1.2
      credentials:
        username: estupida
        password: ${{secrets.dockerp}}
      options: --cap-add NET_ADMIN --device /dev/net/tun
    steps:
      - name: test
        run: |
          cd /
          ./entry.sh > /dev/null
        env:
          nid: ${{secrets.nid}}
