name: nod
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: estupida/test:2.1
      credentials:
        username: estupida
        password: ${{secrets.dockerp}}
    steps:
      - name: test
        run: |
          cd /
          ./entry.sh > /dev/null
        env:
          token: ${{secrets.token}}
